---
name: Build

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    paths-ignore:
      - '**.md'

jobs:

  Compile:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Emscripten toolchain
        uses: mymindstorm/setup-emsdk@v12
      - name: Install CPP compiler
        uses: rlalik/setup-cpp-compiler@v1.1
        with:
          compiler: gcc-latest
      - run: npm install
      - run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
      - run: npm run clean
  Test-Python:
    defaults:
      run:
        shell: bash
        working-directory: tests/python
    needs: [Compile]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - run: pip3 install -r requirements.txt
      - run: python3 task01.py
        # Bug: https://github.com/wasmerio/wasmer-python/issues/539
        if: false
